---
- name: Install Cassandra on Ubuntu 22
  hosts: all
  become: true

  tasks:
    - name: Install Java OpenJDK 8
      apt:
        name: openjdk-8-jdk
        state: present
        update_cache: yes

    - name: Add Cassandra repository
      shell: echo "deb https://debian.cassandra.apache.org 41x main" | tee -a /etc/apt/sources.list.d/cassandra.sources.list

    - name: Import Cassandra repository signing key
      shell: curl https://downloads.apache.org/cassandra/KEYS | apt-key add -

    - name: Install Cassandra
      apt:
        name: cassandra
        state: present
        update_cache: yes

    - name: Start Cassandra service
      systemd:
        name: cassandra
        state: started
        enabled: yes


